baseurl: "https://wangzhefeng.com/"
languageCode: zh-cn
title: "wangzf"
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: "wangzf"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: ↩
rssLimit: 100

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/post/"
      weight: 3
    - name: "笔记"
      url: "/note/"
      weight: 4
    # - name: "分类"
      # url: "/categories/"
      # weight: 5
    - name: "简历"
      url: "/resume/"
      weight: 6
    - name: "事务"
      url: "/todo/"
      weight: 7
    - name: "主题"
      url: "/Ivy/"
      weight: 8
    # - name: "标签"
      # url: "/tags/"
      # weight: 9
    # - name: "订阅"
      # url: "/index.xml"
      # weight: 5

params:
  description: ""
  footer: "&copy; [Zhefeng Wang](https://wangzhefeng.com) 2022 | [GitHub](https://github.com/wangzhefeng)"
  disqusURL: "https://wangzhefeng.com/"
  # costomJS: TODO
  githubContentURL: "https://github.com/wangzhefeng"
  twitterImage: "/images/logo.jpg"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex", "python", "bash", "shell"]
  highlightjsTheme: "github" # atom-one-dark, github
  highlightjsVersion: "9.12.0"
  utteranc:
    enable: false
    repo: wangzhefeng/blog_comment
    issueTerm: pathname
    theme: github-light
  logo:
    img: "/images/logo.jpg"
    url: "/"
    alt: "Zhefeng Wang"
    tag: "log"

# author:
#     en: "Zhefeng Wang"
#     cn: "王哲峰"
#     animation: "Zhefeng Wang"

# lang:
#     edit:
#       cn: "编辑"
#     license:
#       cn: "版权"
#     subscribe:
#       cn: "订阅"

# blackfriday:
#     extensionsmask: ["noIntraEmphasis"]
#     fractions: false


# HTML 渲染
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1

