baseurl: https://wangzhefeng.com/
languageCode: zh-cn
title: wangzf|王哲峰
theme: hugo-ivy
disqusShortname: wangzf
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: ↩
rssLimit: 100

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    - name: "日志"
      url: "/post/"
      weight: 3
    - name: "笔记"
      url: "/note/"
      weight: 4
    - name: "诗词"
      url: "/pomes/"
      weight: 5
    - name: "分类"
      url: "/categories/"
      weight: 6
    - name: "事务"
      url: "/todo/"
      weight: 7
    - name: "简历"
      url: "/resume/"
      weight: 8
    - name: "主题"
      url: "/Ivy/"
      weight: 9
    # - name: "标签"
      # url: "/tags/"
      # weight: 9
    # - name: "订阅"
      # url: "/index.xml"
      # weight: 5

params:
  description: ""
  footer: "&copy; [wangzf](https://wangzhefeng.com) 2023 | [<img src='https://simpleicons.org/icons/github.svg' width='3%'>](https://github.com/wangzhefeng)"
  disqusURL: "https://wangzhefeng.com/"
  githubContentURL: "https://github.com/wangzhefeng"
  twitterImage: "/images/logo.jpg"
  # options for highlight.js (version, additional languages, and theme)
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex", "python", "bash", "shell", "cpp"]
  highlightjsTheme: "github" # "atom-one-dark"
  highlightjsVersion: "9.12.0"
  # logo TODO
  logo:
    img: "images/logo.jpg"
    url: "/"
    alt: "logo"
    tag: ""
  # comment
  utteranc: 
    enable: true
    repo: wangzhefeng/blog_comment
    issueTerm: pathname
    theme: github-light
  gitment: 
    # enable: true
    # owner: wangzhefeng
    # repo: wangzhefeng/blog_comment
    # oauth:
    #   clientId: 3df576922ac49beba8b8
    #   clientSecret: 22d1cf6a6bc31fb1e2ed0bc7ae0e757859c22080


blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

# HTML 渲染
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
