baseurl: "https://wangzhefeng.com/"
languageCode: zh-cn
title: "wangzf"
theme: "hugo-ivy"
googleAnalytics: ""
# disqusShortname: "zhefeng"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: ↩
rssLimit: 100

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2
    # - name: "标签"
      # url: "/tags/"
      # weight: 3
    - name: "分类"
      url: "/categories/"
      weight: 3
    - name: "简历"
      url: "/resume/"
      weight: 4
    - name: "主题"
      url: "/Ivy/"
      weight: 5
    # - name: "订阅"
      # url: "/index.xml"
      # weight: 5

params:
  description: ""
  footer: "&copy; [Zhefeng Wang](https://wangzhefeng.com) 2021 - 2022 | [GitHub](https://github.com/wangzhefeng)"
  # disqusURL: "wangzhefeng.com/"
  # costomJS:
  githubContentURL: "https://github.com/wangzhefeng"
  twitterImage: "/images/logo.jpg"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"
  highlightjsVersion: "9.12.0"

logo:
    en:
      img: "/images/logo.jpg"
      url: "/"
      alt: "Zhefeng Wang"
      tag: ""

# author:
#     en: "Zhefeng Wang"
#     cn: "王哲峰"
#     animation: "Zhefeng Wang"

# lang:
#     edit:
#       cn: "编辑"
#     license:
#       cn: "版权"
#     subscribe:
#       cn: "订阅"

# blackfriday:
#     extensionsmask: ["noIntraEmphasis"]
#     fractions: false

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1