[build]
command = 'npm ci && npm run build'
publish = 'public'
[build.environment]
HUGO_VERSION = '0.134.1'


[context]
[context.branch-deploy]
command = 'npm ci && hugo -F -b $DEPLOY_PRIME_URL && npx pagefind --site public'

[context.deploy-preview]
command = 'npm ci && hugo -F -b $DEPLOY_PRIME_URL && npx pagefind --site public'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
