---
title: React
author: 王哲峰
date: '2015-11-20'
slug: react
categories:
  - 前端
  - javascript
tags:
  - tool
output:
  blogdown::html_page:
    toc: true
    fig_width: 6
    dev: "svg"
---

- React 基础
- React-Router
- PubSub
- Redux
- Ant-Design

# 1.React 简介

## 1.1 React 是什么

- React：用于构建用户界面的 JavaScript 库
- React：是一个将数据渲染为 HTML 视图的开源 JavaScript 库

    - 1.发送请求获取数据
    - 2.处理数据(锅炉、整理格式)
    - 3.操作 DOM 呈现页面(React 不做)

## 1.2 React 是谁开发的

- 由 Facebook 开发，且开源

## 1.3 React 为什么要学

- 1.原生 JavaScript 操作 DOM 繁琐、效率低(DOM-API 操纵 UI)
- 2.使用 JavaScript 直接操作 DOM，浏览器会进行大量的重绘重排
- 3.原生 JavaScript 没有组件化编码方案，代码复用率低

## 1.4 React 的特点


- 1.采用组件化模式、声明式编码，提高开发效率及组件复用率
- 2.在 React Native 中可以使用 React 语法进行移动端开发
- 3.使用虚拟 DOM + 优秀的 Diffing 算法，尽量减少与真实 DOM 的交互

## 1.5 学习 React 之前需要掌握的 JavaScript 基础知识

- 判断 this 的指向
- class
- ES6 语法规范
- npm 包管理器
- 原型、原型链
- 数组常用方法
- 模块化
- jsx

# 2.React 入门

## 1.1 官网

- https://zh-hans.reactjs.org/

## 1.2 基本使用

### 1.2.1 相关 js 库

- ``babel.min.js``
    - ES6 => ES5
    - jsx => js
- ``prop-type.js``
- ``react.development.js``
    - 核心库
- ``react-dom.development.js``
    - 扩展库，操作 DOM

### 1.2.2 创建虚拟DOM的两种方式

- 1.纯 js 方式(一般不用)
- 2.jsx 方式

### 1.2.3 JSX 

- 1.全称 JavaScript XML
- 2.React 定义的一种类似于 XML 的 js 扩展语法：JS+XML
- 3.本质是 React.createElement(component, props, ...children)方法的语法糖
- 4.作用：用来简化创建虚拟 DOM
    - a.写法：``val ele = <h1>Hello JSX!</h1>``
    - b.注意1：它不是字符串，也不是 HTML/XML 标签
    - c.注意2：它最终产生的就是一个 js 对象
- 5.标签名任意：HTML 标签或其他标签
